export const theme = {
  colors: {
    primary:        '#4A90D9',
    primaryDark:    '#2F6FB5',
    bg:             '#F2F6F3',
    card:           '#FFFFFF',
    text:           '#1A2B3C',
    textMuted:      '#5E6E82',
    textLight:      '#94A3B8',
    tintBlue:       '#E6F1FB',
    tintBlueIcon:   '#2F6FB5',
    tintYellow:     '#FEF6E0',
    tintYellowIcon: '#B8860B',
    tintPeach:      '#FCEBE3',
    tintPeachIcon:  '#C25A34',
    tintMint:       '#E4F5EE',
    tintMintIcon:   '#1D9E75',
    tintLilac:      '#EEEBFB',
    tintLilacIcon:  '#6B5DD3',
    danger:         '#A32D2D',
    dangerBg:       '#FFF3F3',
    border:         'rgba(26,34,51,0.08)',
    surfaceAlt:     '#EEF1F4',
    promoBg:        '#EDF4FC',
  },
  radius: {
    sm:   12,
    md:   16,
    lg:   20,
    pill: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
  font: {
    regular:  'Poppins_400Regular',
    medium:   'Poppins_500Medium',
    semibold: 'Poppins_600SemiBold',
    bold:     'Poppins_700Bold',
  },
  shadow: {
    shadowColor:   '#1A2B3C',
    shadowOpacity: 0.06,
    shadowRadius:  12,
    shadowOffset:  { width: 0, height: 4 },
    elevation:     3,
  },
} as const;
